# Dockerfile
FROM python:3.12-slim

# Instalar dependências do sistema, se necessário
RUN apt-get update && apt-get install -y build-essential

WORKDIR /workspace

# Copiar os arquivos do projeto
COPY . .

RUN pip install --upgrade pip && pip install -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
